---

- src: https://github.com/alvistack/ansible-role-python
  version: develop

- src: https://github.com/alvistack/ansible-role-apt
  version: develop

- src: https://github.com/alvistack/ansible-role-yum
  version: develop
