---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#- name: yum-config-manager --add-repo
#  yum_repository:
#    baseurl: "{{ item.baseurl | default(None) or omit }}"
#    description: "{{ item.description | default(None) or omit }}"
#    enabled: "{{ item.enabled | default(None) or omit }}"
#    file: "{{ item.file | default(None) or omit }}"
#    gpgcheck: "{{ item.gpgcheck | default(None) or omit }}"
#    gpgkey: "{{ item.gpgkey | default(None) or omit }}"
#    metadata_expire: "{{ item.metadata_expire | default(None) or omit }}"
#    name: "{{ item.name | default(None) or omit }}"
#    repo_gpgcheck: "{{ item.repo_gpgcheck | default(None) or omit }}"
#    sslcacert: "{{ item.sslcacert | default(None) or omit }}"
#    sslverify: "{{ item.sslverify | default(None) or omit }}"
#  with_items: "{{ _yum_repository }}"
#  tags: etcd
#
#- name: yum install
#  yum:
#    name: "{{ item.name }}"
#    state: "{{ item.state }}"
#  with_items: "{{ _yum }}"
#  tags: etcd
#
#- name: yum -y clean all
#  shell: |
#    yum -y clean all
#  changed_when: false
#  tags: etcd
